"""Search plan models — generated by LLM from the user question."""

from __future__ import annotations

from typing import Dict, List, Optional

from pydantic import BaseModel, Field


class SearchQuery(BaseModel):
    """A single structured search query."""

    query_string: str = Field(description="The actual search string for academic APIs")
    rationale: str = Field(description="Why this query helps answer the research question")
    keywords: List[str] = Field(default_factory=list, description="Core keywords in this query")


class InclusionExclusionCriteria(BaseModel):
    """Criteria for including or excluding papers."""

    include: List[str] = Field(
        default_factory=list,
        description="Criteria that papers must meet to be included",
    )
    exclude: List[str] = Field(
        default_factory=list,
        description="Criteria that disqualify a paper",
    )


class SearchPlan(BaseModel):
    """Structured search plan produced by the LLM."""

    research_topic: str = Field(description="Refined research topic from the question")
    core_concepts: List[str] = Field(description="Core concepts identified")
    synonyms: Dict[str, List[str]] = Field(
        default_factory=dict,
        description="Concept -> list of synonyms",
    )
    queries: List[SearchQuery] = Field(
        default_factory=list,
        description="3-6 structured search queries",
        min_length=1,
        max_length=6,
    )
    year_from: Optional[int] = Field(default=None, description="Inclusive start year")
    year_to: Optional[int] = Field(default=None, description="Inclusive end year")
    domains: List[str] = Field(
        default_factory=list,
        description="Academic domains to focus on, e.g. ['cs.CL', 'cs.AI']",
    )
    criteria: InclusionExclusionCriteria = Field(
        default_factory=InclusionExclusionCriteria,
    )

    def all_query_strings(self) -> List[str]:
        return [q.query_string for q in self.queries]
